#!/usr/bin/env bash

set -e

role=${CONTAINER_ROLE:-api}

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else


    /usr/bin/composer install
    php artisan optimize
    if [ "$role" = "api" ]; then

        php artisan migrate:fresh --seed

        echo "Running the app..."
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf

    elif [ "$role" = "watcher" ]; then

        echo "Running the watcher..."
        /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord-worker.conf
    else
        echo "Could not match the container role \"$role\""
        exit 1
    fi

fi
